### ISSUE TITLE
Many to Many Support

### ISSUE THREAD

**Issue by saifelokour** [evadne/etso#8]
Hello,

I've created a minimal test to show how the library does not currently support `many_to_many` in Ecto schemas using the Northwind Demo. Here's the output:
<img width="1022" alt="image" src="https://user-images.githubusercontent.com/18610228/101030003-dffec080-3581-11eb-8afc-a94e3fba1dad.png">

I've also created a [PR](https://github.com/evadne/etso/pull/9) in hopes that I could get some guidance on how we might go about adding support for this feature. 

The issue seems to be in that the build conditions function head is hard coded here: https://github.com/evadne/etso/blob/f25bdea063893328272adb14004a95973ad7f007/lib/etso/ets/match_specification.ex#L57

However it's not clear how I might change this to support many_to_many.

Please let me know if I can provide more information.

Thanks :)

**Comment by evadne** [comment]
I shall close this as the Pull Request as been opened.
